apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-testing-multiple-components-long-name-5zcg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-testing-multiple-components-long-name-5zcg
    app.kubernetes.io/part-of: testing-multiple-components-long-name
  name: python-testing-multiple-ckgz4
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: python-testing-multiple-components-long-name-5zcg
    weight: null
status: {}
