apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-testing-multiple-components-long-name-5zcg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-testing-multiple-components-long-name-5zcg
    app.kubernetes.io/part-of: testing-multiple-components-long-name
  name: python-testing-multiple-components-long-name-5zcg
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: python-testing-multiple-components-long-name-5zcg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: python-testing-multiple-components-long-name-5zcg
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rsoaresd-tenant/testing-multiple-components-long-name/python-testing-multiple-components-long-name-5zcg@sha256:da5b6746f6a2908d04639d170e63f3edc33a56d7c8a8d0a251cf0f20fffccec1
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
