apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-testing-multiple-components-long-name-5zcg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-testing-multiple-components-long-name-5zcg
    app.kubernetes.io/part-of: testing-multiple-components-long-name
  name: python-testing-multiple-components-long-name-5zcg
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: python-testing-multiple-components-long-name-5zcg
status:
  loadBalancer: {}
