apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-testing-multiple-components-long-name-8xjy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-testing-multiple-components-long-name-8xjy
    app.kubernetes.io/part-of: testing-multiple-components-long-name
  name: java-testing-multiple-components-long-name-8xjy
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: java-springboot-app
    app.kubernetes.io/instance: java-testing-multiple-components-long-name-8xjy
status:
  loadBalancer: {}
